stages:
  - test
  - assembly
  - release

default:
  image: registry.mdcatapult.io/informatics/docker-images/ci:scala-v1.1.0

test:
  stage: test
  tags:
    - wopr
  script:
    - sbt +clean coverage +test coverageReport
  coverage: /\[info\]\sAll\sdone\.\sCoverage was\s\[(\d.*)%\]/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

assemble:
  stage: assembly
  tags:
    - wopr
  script:
    - sbt assembly
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  tags:
    - wopr
  script:
    - /scripts/release.sh -b
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release-jar:
  stage: release
  tags:
    - wopr
  script:
    - sbt assembly
    - /scripts/upload-files.sh 'target/scala-2.12/*.jar' $CI_COMMIT_REF_NAME
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/